-- AlterTable
ALTER TABLE `DETAIL_RESERVASI_FASILITAS` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `DETAIL_RESERVASI_KAMAR` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
