steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Build started at $(date)" && docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} . && echo "Build ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Test started at $(date)" && docker run ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} npm run test && echo "Test ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: push
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Push started at $(date)" && docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && echo "Push ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy
  entrypoint: 'bash'
  secretEnv: ['KEY', 'MYSQL', 'PORT']
  args:
    - '-c'
    - |
      set -e
      echo "Deploy started at $(date)"
      gcloud auth configure-docker
      gcloud compute ssh ${_VM_USER}@${_VM_NAME} --zone=${_ZONE} --command "sh -c 'docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && \
              docker stop app || true && \
              docker rm app || true && \
              docker run -d --name app \
              --env-file /workspace/KEY \
              --env-file /workspace/MYSQL \
              --env-file /workspace/PORT \
              ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG}'"
      echo "Deploy ended at $(date)"
