steps:
# Instalasi dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Migrate Prisma
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npx'
  args: ['prisma', 'migrate', 'dev', '--name', 'initvm']

# Deploy aplikasi ke App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']

# Set Environment
  env:
      - 'SECRET_VALUE=_SECRET'