steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Migrate Prisma
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npx'
  args: [
    'prisma',
    'migrate',
    'dev',
    '--name',
    'initvm'
  ]
  env:
    - 'SECRET_VALUE=${_SECRET}'

# Deploy the application to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']