substitutions:
  _REGION: asia-southeast1
  _VM_USER: veapee
  _VM_NAME: aplikasi-testing-ci-cd
  _ZONE: asia-southeast1-a
  _IMAGE_NAME: app
  _IMAGE_TAG: $COMMIT_SHA
  _SECRET_KEY: KEY
  _SECRET_PORT: PORT
  _SECRET_MYSQL: MYSQL

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Build started at $(date)" && docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} . && echo "Build ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: fetch-secrets
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Fetching secrets started at $(date)" && 
       export SECRET_KEY=$(gcloud secrets versions access latest --secret=${_SECRET_KEY}) &&
       export SECRET_PORT=$(gcloud secrets versions access latest --secret=${_SECRET_PORT}) &&
       export SECRET_MYSQL=$(gcloud secrets versions access latest --secret=${_SECRET_MYSQL}) &&
       echo "Fetching secrets ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Test started at $(date)" && docker run -e KEY=$SECRET_KEY -e PORT=$SECRET_PORT -e MYSQL=$SECRET_MYSQL ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} npm run test && echo "Test ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: push
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Push started at $(date)" && docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && echo "Push ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Deploy started at $(date)" && 
      gcloud auth configure-docker && 
      gcloud compute ssh ${_VM_USER}@${_VM_NAME} --zone=${_ZONE} --command 
      "docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && 
      docker stop app || true && docker rm app || true && 
      docker run -d --name app -e KEY=$SECRET_KEY -e PORT=$SECRET_PORT -e MYSQL=$SECRET_MYSQL ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG}" && 
      echo "Deploy ended at $(date)"'
    ]
