substitutions:
  _REGION: asia-southeast1
  _VM_USER: vincentius_vap
  _VM_NAME: aplikasi-testing-ci-cd
  _ZONE: asia-southeast1-a
  _IMAGE_NAME: app
  _IMAGE_TAG: $COMMIT_SHA

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Build started at $(date)" && 
      docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} . && echo "Build ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Test started at $(date)" && 
      docker run ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} npm run test && 
      echo "Test ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: push
  entrypoint: 'sh'
  args:
    [
      '-c',
      'echo "Push started at $(date)" && 
      docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && 
      echo "Push ended at $(date)"'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy
  entrypoint: 'bash'
  secretEnv: ['KEY', 'MYSQL', 'PORT']
  args:
    - '-c'
    - |
      set -e
      echo "Deploy started at $(date)"
      gcloud auth configure-docker

      PORT_FILE=$(mktemp)
      MYSQL_FILE=$(mktemp)
      KEY_FILE=$(mktemp)

      gcloud secrets versions access latest --secret=PORT > $PORT_FILE
      gcloud secrets versions access latest --secret=MYSQL > $MYSQL_FILE
      gcloud secrets versions access latest --secret=KEY > $KEY_FILE
    
      gcloud compute ssh ${_VM_USER}@${_VM_NAME} --zone=${_ZONE} --command "sh -c 'docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG} && \
              docker stop app || true && \
              docker rm app || true && \
              docker run -d --name app \
              -p 5000:5000 \
              -e PORT=\$(cat $PORT_FILE) \
              -e MYSQL=\$(cat $MYSQL_FILE) \
              -e KEY=\$(cat $KEY_FILE) \
              ${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/${_IMAGE_NAME}:${_IMAGE_TAG}'"

      rm -f $PORT_FILE $MYSQL_FILE $KEY_FILE
      
      echo "Deploy ended at $(date)"