steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Set environment variables
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "SECRET_VALUE=${_SECRET}" >> $BUILDER_ENV_FILE

# Migrate Prisma
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npx'
  args: [
    'prisma',
    'migrate',
    'dev',
    '--name',
    'initvm'
  ]
  env:
    - 'SECRET_VALUE=${_SECRET}'

# Deploy the application to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']