apiVersion: skaffold/v4beta8
kind: Config
metadata: 
  name: backend
profiles:
- name: staging
  manifests:
    rawYaml:
    - deploy/staging.yaml
- name: prod
  manifests:
    rawYaml:
    - deploy/prod.yaml

deploy:
  cloudrun: {}