-- CreateTable
CREATE TABLE `AKUN` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `roleId` INTEGER NOT NULL,
    `username` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `AKUN_username_key`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CUSTOMER` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `akunId` INTEGER NULL,
    `jenis_customer` VARCHAR(191) NOT NULL,
    `nama_customer` VARCHAR(191) NOT NULL,
    `nama_institusi` VARCHAR(191) NOT NULL,
    `nomor_identitas` VARCHAR(191) NOT NULL,
    `nomor_telepon` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `alamat` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETAIL_KAMAR` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `kamarId` INTEGER NOT NULL,
    `nomor_kamar` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETAIL_RESERVASI_FASILITAS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reservasiId` INTEGER NOT NULL,
    `fasilitasId` INTEGER NOT NULL,
    `jumlah` INTEGER NULL,
    `subtotal` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETAIL_RESERVASI_KAMAR` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `kamarId` INTEGER NOT NULL,
    `reservasiId` INTEGER NOT NULL,
    `jumlah` INTEGER NULL,
    `subtotal` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FASILITAS_TAMBAHAN` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama_fasilitas` VARCHAR(191) NOT NULL,
    `satuan` INTEGER NULL,
    `harga` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KAMAR` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `jenisKamar` VARCHAR(191) NOT NULL,
    `jenisBed` VARCHAR(191) NOT NULL,
    `kapasitas` INTEGER NULL,
    `luas` INTEGER NULL,
    `fasilitas` VARCHAR(191) NOT NULL,
    `jumlah_bed` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NOTA_PELUNASAN` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reservasiId` INTEGER NOT NULL,
    `no_invoice` VARCHAR(191) NOT NULL,
    `tax` INTEGER NULL,
    `subtotal` INTEGER NULL,
    `jaminan` INTEGER NULL,
    `deposit` INTEGER NULL,
    `cash` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PEGAWAI` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `akunId` INTEGER NULL,
    `nama` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESERVASI` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `pegawaiId` INTEGER NULL,
    `customerId` INTEGER NULL,
    `tanggal_reservasi` DATETIME(3) NOT NULL,
    `check_in` DATETIME(3) NOT NULL,
    `check_out` DATETIME(3) NOT NULL,
    `jumlahDewasa` INTEGER NULL,
    `jumlahAnakAnak` INTEGER NULL,
    `status` VARCHAR(191) NOT NULL,
    `prefix_reservasi` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `namaRole` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SEASON` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `jenis_season` VARCHAR(191) NOT NULL,
    `tanggal_awal` DATETIME(3) NOT NULL,
    `tanggal_akhir` DATETIME(3) NOT NULL,
    `perubahan_harga` DOUBLE NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TARIF` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `seasonId` INTEGER NOT NULL,
    `kamarId` INTEGER NOT NULL,
    `harga` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AKUN` ADD CONSTRAINT `AKUN_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `ROLE`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CUSTOMER` ADD CONSTRAINT `CUSTOMER_akunId_fkey` FOREIGN KEY (`akunId`) REFERENCES `AKUN`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETAIL_KAMAR` ADD CONSTRAINT `DETAIL_KAMAR_kamarId_fkey` FOREIGN KEY (`kamarId`) REFERENCES `KAMAR`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETAIL_RESERVASI_FASILITAS` ADD CONSTRAINT `DETAIL_RESERVASI_FASILITAS_reservasiId_fkey` FOREIGN KEY (`reservasiId`) REFERENCES `RESERVASI`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETAIL_RESERVASI_FASILITAS` ADD CONSTRAINT `DETAIL_RESERVASI_FASILITAS_fasilitasId_fkey` FOREIGN KEY (`fasilitasId`) REFERENCES `FASILITAS_TAMBAHAN`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETAIL_RESERVASI_KAMAR` ADD CONSTRAINT `DETAIL_RESERVASI_KAMAR_reservasiId_fkey` FOREIGN KEY (`reservasiId`) REFERENCES `RESERVASI`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETAIL_RESERVASI_KAMAR` ADD CONSTRAINT `DETAIL_RESERVASI_KAMAR_kamarId_fkey` FOREIGN KEY (`kamarId`) REFERENCES `KAMAR`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NOTA_PELUNASAN` ADD CONSTRAINT `NOTA_PELUNASAN_reservasiId_fkey` FOREIGN KEY (`reservasiId`) REFERENCES `RESERVASI`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PEGAWAI` ADD CONSTRAINT `PEGAWAI_akunId_fkey` FOREIGN KEY (`akunId`) REFERENCES `AKUN`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESERVASI` ADD CONSTRAINT `RESERVASI_pegawaiId_fkey` FOREIGN KEY (`pegawaiId`) REFERENCES `PEGAWAI`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESERVASI` ADD CONSTRAINT `RESERVASI_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `CUSTOMER`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TARIF` ADD CONSTRAINT `TARIF_seasonId_fkey` FOREIGN KEY (`seasonId`) REFERENCES `SEASON`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TARIF` ADD CONSTRAINT `TARIF_kamarId_fkey` FOREIGN KEY (`kamarId`) REFERENCES `KAMAR`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
