apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prod
spec:
  template:
    spec:
      containers:
        - image: app
          env:
          - name: MYSQL
            valueFrom:
              secretKeyRef:
                key: latest
                name: MYSQL
          - name: PORT
            valueFrom:
              secretKeyRef:
                key: latest
                name: PORT
          - name: KEY
            valueFrom:
              secretKeyRef:
                key: latest
                name: KEY
